package exception

import "fmt"

var NotFoundError = fmt.Errorf("not found error")
